### ISSUE TITLE
Hi, do you have the sample dates ?

### ISSUE THREAD

**Issue by babarlelephant** [emvolz/weifang-sarscov2#1]
Hi, to add [all but 7 of your sequences on nextstrain](https://nextstrain.org/ncov?f_division=Shandong) they'd like some sample dates (because on Gisaid only january and february is indicated and this is too large for the timeline tree of nextstrain)

And we are not sure if https://github.com/emvolz/weifang-sarscov2/blob/master/beast/seir.xml is the dates you obtained with your model or the true ones.  Maybe you can indicate the dates on Gisaid ?

Thank you.

**Comment by babarlelephant** [comment]
Hi again @emvolz

In a Nature paper https://www.nature.com/articles/s41586-020-2355-0_reference.pdf (the tree p. 12) they claim that the collection date of EPI_ISL_413691 (China/WF0001/2020 your WFCDC0001) is in the first few days of January, whereas you estimated that the collection date was 24 January.

Same for  EPI_ISL_413693 (China/WF0003/2020 your WFCDC0003)

You can see their tree here http://ncov.linc.org.cn/ncov/0311/?s=China/WF0001/2020

There are now some press releases mainly based on this non-Wuhan early sequence https://www.globaltimes.cn/content/1189599.shtml

       Chinese scientists find new evidence that Huanan seafood market in Wuhan may not be the origin of the coronavirus

**Comment by emvolz** [comment]
You need to contact xinguang li and qing nie for the sample times. But I agree that none of the Weifang sequences were collected in early January. I hope that was not an important aspect of their nature paper!
